services:
  kafka-exporter:
    container_name: kafka-exporter
    image: docker.io/bitnami/kafka-exporter:latest
    ports:
      - "9308:9308"
    networks:
      - kafka-network
    environment:
      - KAFKA_VERSION=2.8.1
    command: [ "--kafka.server=kafka-0:9092", "--kafka.server=kafka-1:9092", "--kafka.server=kafka-2:9092" ]
    healthcheck:
      test: "bash -c 'printf \"\" > /dev/tcp/127.0.0.1/9308; exit $$?;'"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - kafka-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:9090 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=grafana
      volumes:
        - ./grafana/provisioning:/etc/grafana/provisioning
        - ./grafana/dashboards:/var/lib/grafana/dashboards
      networks:
        - kafka-network
      healthcheck:
        test: curl --fail localhost:3000
        interval: 5s
        timeout: 10s
        retries: 3
        start_period: 10s

volumes:
  prom_data:
    driver: local

networks:
  kafka-network:
    external: true
