version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  python-producer:
    image: python:3.10
    container_name: python-producer
    volumes:
      - ./producer:/app
    working_dir: /app
    command: bash -c "pip install kafka-python && python producer.py"
    depends_on:
      - kafka

  python-consumer:
    image: python:3.10
    container_name: python-consumer
    volumes:
      - ./consumer:/app
    working_dir: /app
    command: bash -c "pip install kafka-python && python consumer.py"
    depends_on:
      - kafka
