version: '3.8'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    image: golang:latest
    build: ./producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:9092"
    deploy:
      replicas: 1  # Simulate 100 producers

  consumer:
    image: golang:latest
    build: ./consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:9092"
    deploy:
      replicas: 1  # Simulate 1000 consumers

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - '9090:9090'

networks:
  localprom:
    driver: bridge

