global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'golang-producer'
    static_configs:
      - targets: ['localhost:8080']  # Producer exposes metrics here
