global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'golang-app'
    static_configs:
      - targets: ['golang_app:8080']
